baseURL: "https://jean-rl.github.io/"
paginate: 5
theme: "papermod"
title: jeanrl # Upper-left title
publishDir: "docs" # Necessary for Github Pages

# enableInlineShortcodes: true

params:
  description: "Hello, friend"
  # author: Me # Prints the author in every post metadata
  profileMode:
    enabled: true # The welcome page is a profile page
    title: "Jeanfed Ramírez"
    subtitle: "Hello there, I'm Jean, and I write mostly about machine learning."
    imageUrl: "images/profile.jpg" # Path relative to the \static directory
    imageWidth: 180
    imageHeight: 180
    imageTitle: "profile-pic"
    buttons:
      - name: About
        url: /about
      - name: Posts # I also like to name this "Posts", the alternative is "Blog"
        url: /posts
      # - name: Portfolio
      #  url: /projects

  socialIcons:
    - name: github
      url: "https://github.com/jean-rl"
    - name: twitter
      url: "https://twitter.com/jeanrl__"
    - name: email
      url: "mailto://jeanfed.ramirez@gmail.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/jeanfed-ramirez/"

  assets:
    favicon: "images/favicon.ico" # https://es.wikipedia.org/wiki/Favicon
    favicon16x16: "images/favicon-16x16.png"
    favicon32x32: "images/favicon-32x32.png"
    apple_touch_icon: "images/apple-touch-icon.png"

menu:
  main:
      - name: About
        url: about/
        weight: 10
      - name: Posts
        url: posts/
        weight: 20
      # - name: Portfolio
      #  url: projects/
      #  weight: 30